on:
  pull_request:

jobs:
  build:
    runs-on: native
    strategy:
      matrix:
        host: ["kura", "apple", "bananacreme", "cherry", "pumpkin"]
    steps:
      - uses: actions/checkout@v4
      - run: make HOST=${{ matrix.host }} build
