on:
  pull_request:

jobs:
  build:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - name: Determine hosts
        run: echo "BUILD_HOSTS=$(nix flake show --json | jq '.nixosConfigurations | keys | .[]' -r)" >> $FORGEJO_ENV
      - run: echo "build list:" ${{ env.BUILD_HOSTS }}
      - uses: ./.forgejo/actions/nix-build
        with:
          hosts: ${{ env.BUILD_HOSTS }}
  notify:
    if: always()
    runs-on: native
    needs: 
      - build
    steps:
      - uses: Cadair/matrix-notify-action@main
        id: message
        with:
          matrix_token: ${{ secrets.matrix_access_token }}
          github_token: ${{ secrets.FORGEJO_TOKEN }}
          homeserver: "https://chat.joukamachi.net"
          roomid: "!GaSl6XbFt4d6DYNUVb:joukamachi.net"
      - name: Print event ID
        run: echo "Sent Matrix event '${{ steps.message.outputs.eventId }}'"
